### ISSUE TITLE
Does anyone really needs ligatures support?

### ISSUE THREAD

**Issue by puzrin** [fontello/fontello#103]
It's not a big problem to add ligatues support. But, IMHO, this is good for single effective demonstration, and absolutely useless anymore :) . Because of:
- bad crossbrowser support
- bad flexibility (you can't change ligatures without font regeneration)

But... if someone will <del>pay100500usd</del> explain the practical profit of ligatures, i'll try to add those on the next iteration.

If you have cases, when ligatures are useful - let me know.

**Comment by rkingon** [comment]
Another use case for ligature...

If you want to be able to use icons without creating an element, it's much easier if you have the ligatures... 

ie:
```scss
@mixin icon($icon) {
    font-family: 'your-icon-font';
    content: $icon;
    /* Other css to make it display properly */
}
.menu {
   @include("ligature-for-menu");
   /* Any other css needed */
}
```

Any update on getting it in? Would also be helpful for designers to use in photoshop (mentioned before, but seriously, it would! My designers don't like when I use these icon fonts because they can't remember the chars for each)
