### ISSUE TITLE
embedded.css Base64

### ISSUE THREAD

**Issue by emiledesad** [fontello/fontello#238]
Steps to reproduce:
1) Go to http://fontello.com and select icons
2) Download webfont
3) Open file /css/*-embedded.css
4) Look at @font-face rule, it shoud have Base64 code instade of  [object Object] and  [object Uint8Array]

``` css
@font-face {
  font-family: 'fontello';
  src: url('data:application/octet-stream;base64, [object Object]') format('woff'),
         url('data:application/octet-stream;base64, [object Uint8Array]') format('truetype');
}
```
