### ISSUE TITLE
Icons, that has icon symbol in content attribute does not appears on the page

### ISSUE THREAD

**Issue by meliborn** [fontello/fontello#251]
Really weird case. In one moment on my server, some of the icons stopped to display. I found, that it's happened with icons, that has this definitions in fontello.css file

``` css
.icon-award:before { content: 'some strange icon'; } /* '\1f3c9' */
```

If I replace it by `\1f3c9` everything ok. So what the problem is?
