### ISSUE TITLE
Font weight bold if parents position is fixed

### ISSUE THREAD

**Issue by PatrickVerwoerd** [fontello/fontello#273]
I use the icons in the header of a website that I want to position fixed but unfortunately the icons then appear bold. Once I undo position:fixed; the problem is solved, but that's not the solution I'm waiting for. The header should be positioned fixed.

Fixed parent:
![fixed](https://f.cloud.github.com/assets/5353413/2510501/1dc1c870-b408-11e3-8928-e7b0cfcb0070.png)
No fixed parent:
![not-fixed](https://f.cloud.github.com/assets/5353413/2510502/1dc8b75c-b408-11e3-97ee-c49433547d52.png)

This is my css:

``` css
header .icon {
    font-family: 'strict-icon';
    float: left;
    margin: 6px 0 6px 6px;
    color: #fff;
    width: 30px;
    line-height: 30px;
    height: 30px;
    font-size: 1.35em;
    background: #535b5f;
    text-align: center;
    display: block;
    text-decoration: none;
}
```

``` css
@font-face {
  font-family: 'strict-icon';
  src: url('font/strict-icons.eot');
  src: url('font/strict-icons.eot#iefix') format('embedded-opentype'),
       url('font/strict-icons.woff') format('woff'),
       url('font/strict-icons.ttf') format('truetype'),
       url('font/strict-icons.svg#strict-icon') format('svg');
  font-weight: normal;
  font-style: normal;
}
/* Chrome hack: SVG is rendered more smooth in Windozze. 100% magic, uncomment if you need it. */
/* Note, that will break hinting! In other OS-es font will be not as sharp as it could be */
/*
@media screen and (-webkit-min-device-pixel-ratio:0) {
  @font-face {
  font-family: 'strict-icon';
    src: url('font/strict-icons.svg#strict-icon') format('svg');
  }
}
*/
```
