### ISSUE TITLE
Feature request: More names for one icon (alias)

### ISSUE THREAD

**Issue by Mephiztopheles** [fontello/fontello#373]
Hi,
I use different classes based on objectClasses from database and therefore I need more names (selectors) for one icon
e.g.

``` CSS
.icon-file-docx:before,
.icon-file-doc:before { content: '\e809'; }
```

It would be nice, if I can enter more than one name ("customize name"-tab on your homepage) for each icon, so I can simply copy the new files into my system and don't need to edit them everytime
