### ISSUE TITLE
(Feature request) Allow styles to be named after their unicode 4-bytes

### ISSUE THREAD

**Issue by amenadiel** [fontello/fontello#391]
I wish that current stylesheet would allow using fontello-{{4 bytes}} to identify a style. For example, instead of:

```css
.fontello-gplus:before { content: '\e800'; }
.fontello-pinboard:before { content: '\e801'; }
.fontello-cloudapp:before { content: '\e802'; }
.fontello-right-dir:before { content: '\e803'; }
.fontello-fuel:before { content: '\e804'; }
```

the stylesheet would say

```css
.fontello-gplus:before, .fontello-E800:before { content: '\e800'; }
.fontello-pinboard:before, .fontello-E801:before { content: '\e801'; }
.fontello-cloudapp:before, .fontello-E802:before { content: '\e802'; }
.fontello-right-dir:before, .fontello-E803:before { content: '\e803'; }
.fontello-fuel:before, .fontello-E804:before { content: '\e804'; }
```

I'm doing this manually each time I download fontello, and I need it because the 4 digit code + the TTF font file allows to create individual images, for example using a blank marker and PHP's [ImageTTFText](http://php.net/manual/es/function.imagettftext.php). But I still need one way to associate the 4 digit code with the image of the legend with pure CSS.
