### ISSUE TITLE
Remove font paths from `fontello-embedded.css` 

### ISSUE THREAD

**Issue by xpepermint** [fontello/fontello#422]
I use fontello fonts with `webpack`. To omit complications I import `fontello-embedded.css` into my project but I have to delete the

```css
@font-face {
  font-family: 'fontello';
  src: url('../font/fontello.eot?223208');
  src: url('../font/fontello.eot?223208#iefix') format('embedded-opentype'),
       url('../font/fontello.svg?223208#fontello') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

part every time I make changes. I would appreciate if we can have `embedded` file with only embedded data without paths.
