### ISSUE TITLE
Glyph vertical alignment different than some FontAwesome icons.

### ISSUE THREAD

**Issue by Kravimir** [fontello/fontello#513]
I noticed the difference on the angle-right and angle-left icons ('\f105' and '\f104'). I can adjust the vertical alignment in the stylesheet on a case by case basis, but it would much better if Fontello could be dropped in as a replacement for Font Awesome without needing fine-tuning like that.

Changing the "Units per em" and "Ascent" font metrics to match Font Awesome (1792 and 1536, respectively) didn't seem to make a difference.

Anyway, thanks for providing this great tool/resource.

**Comment by puzrin** [comment]
I'd suggest 2 things:

- vary `baseline` in advanced settings, FA uses 14.2857143%
- disable or enable hinting (don't know if FA use it)

If that does not help, then metrics compare with `ttx` utility required.

**Comment by r0b-** [comment]
Strange, the only way I had nearly similar results across browsers was to set baseline to 0...
(Font with 5 social media icons from FA)

**Comment by ohjames** [comment]
I'm seeing differing vertical alignment in all browsers compared to FontAwesome. Some glyphs are a little lower than their FA counterparts (fa-arrow-up) and some are a little higher.

**Comment by misotolar** [comment]
Not sure if related, but i had issues with some vertically subaligned FA icons (fa-download, fa-cogs, fa-power-off) in _Windows_ browsers only (tested with Chrome, Firefox, Edge).

After disable hinting as suggested, vertical align is ok:

![issue](https://user-images.githubusercontent.com/2345018/56763954-dd33cb00-67a3-11e9-912f-daa59a4ec2f1.png)

**Comment by Jieiku** [comment]
seems to be exactly the problem I am having, have not yet figured out what hinting is or how to disable it.

I think hinting is the aliasing and shading affects, which I already disabled.

In my case I was able to fix the alignment with `vertical-align`:

```scss
[class^="icon-"]:before, [class*=" icon-"]:before {
  vertical-align: 1em;
```

I came to this solution after seeing the following block in the font-awesome _mixins.scss file:

```scss
// sets relative font-sizing and alignment (in _sizing)
@mixin fa-size ($font-size) {
  font-size: fa-divide($font-size, $fa-size-scale-base) * 1em; // converts step in sizing scale into an em-based value that's relative to the scale's base
  line-height: fa-divide(1, $font-size) * 1em; // sets the line-height of the icon back to that of it's parent
  vertical-align: (fa-divide(6, $font-size) - fa-divide(3, 8)) * 1em; // vertically centers the icon taking into account the surrounding text's descender
}
```
