### ISSUE TITLE
CSS Module Support?

### ISSUE THREAD

**Issue by jamiehutber** [fontello/fontello#517]
This is an extremely nice to have. But as I have started using webpack I struggled for a long time to get fontello working. Then I realised I was going about it completely the wrong way.

Take a simple example:

````css
[class^="icon-"]:before, [class*=" icon-"]:before {
  font-family: "fontello";
  font-style: normal; 
    .....
  /* text-shadow: 1px 1px 1px rgba(127, 127, 127, 0.3); */
}
.icon-logo:before { content: '\e800'; } /* '' */
````

This won't work because css modules won't understand the selector: [class^="icon-"]:before, [class*=" icon-"]:before {

So I now have to make sure everything is bundled up so when exported as an object the selectors are valid:

````css
.icon-logo:before, .icon-logo:before {
.....
}
.icon-logo:before { content: '\e800'; } /* '' */
``````

Now of course my webfont works. I wonder if there any thing we can do to bundle it up like this? Of course, we'll have larger selectors. But less trouble once I get more than 1 font 💃 

Cheers guys
