### ISSUE TITLE
Icon class needs a box character to work

### ISSUE THREAD

**Issue by doorman02** [fontello/fontello#518]
Hello, in the generated demo project the icon is represented in the following way with a character code box.
`<i class="demo-icon icon-star"></i>`
If I remove the  the icon disappears. How can I use the icon without the  character?
Like this...
`<i class="icon-star"></i>`

Thanks!

**Comment by JohnEcks** [comment]
you can do it two ways.

1) you can use CSS pseudo element on anything, like `.myClass:before`, `.myClass:after`, etc. I use this for headings and buttons. In your case you might do something `i:before`. You might need a non-breaking space though. If doing this myself, I would use a `<span>`  with the custom character I set (see below 2), like `<p><span>a</span></p>` and then just set my span in css to `p span { font-family: my_icons }. I find that using custom codes and custom font names is the easiest, and I usually append my in-house project codes to the font names to make sure there's no conflict on users' systems.

2) On fontello website, choose your icons, then go to "customize codes" tab, and change the codes to whatever you want (the top of the box for each icon). The bottom box will automatically update depending on what character you put in the top box.

hope that helps.

**Comment by doorman02** [comment]
Thanks for the answer, but I was hoping I could just use it out of the box without caring about the underlying character code. The same way as Font Awesome does it, you can use their icons right away like this  `<i class="fa fa-camera-retro"></i>`
In the same way as FA, is this possible with the custom generated Fontello fontset?

**Comment by JohnEcks** [comment]
I'm sure there is, but I never used it that way.

You can customize those names similar to FA though. Maybe try that? I think there's notes in the CSS file comments too about setting up various ways.

**Comment by JohnEcks** [comment]
If you're still looking how to do this...

All you need to do is include the CSS from fontello with pseudo elements. I actually needed to use this from something today and it worked just fine. It's the same as I mentioned before, you're just adding the pseudo elements to all classes that contain "icon-" by default. 

`<i class="icon-heart></i>`

```css
[class^="icon-"]:before, [class*=" icon-"]:before, { font-family: "my_font"; font-style: normal; font-weight: normal; speak: none; display: inline-block; text-decoration: inherit }

.icon-heart:before { content: '\48'; }
```

I set mine up a little different with custom characters, and so I could use them as`:before` and `:after` but there's nothing wrong with the code included when you generate the fonts. Just add the code as a class to whatever you want and adjust css as needed.

**Comment by doorman02** [comment]
Great thanks I will try this later on :)

**Comment by JohnEcks** [comment]
no worries ;)

btw, the css is included in the downloaded zip in the css folder. It will have the name of your font. So if you named it `my_icons` the css file is `my_icons.css`. I don't use all the CSS as I already have resets in my primary CSS.

btw, you may find this useful. I added `:before` and `:after` CSS so that when I add my icons to buttons I can choose which side they are on based on class, with proper margins. In order to do that, I just added new code names in the css. You could probably do this other ways, but this works fine for me.

Below you'll see how I do this. Icons I need for buttons have `-a` and `-b` variants for before and after. If the margins pose problems you can override where needed, or just have the variants plus the normal icons like `.icon-blah, .icon-blah-a, .icon-blah-b` as shown below. This way you won't get any funkiness with margins on your `<i>` tags.

HTML:
```html
<i class="icon-heart"></i>
<a class="my-button icon-heart-b">do something</a> <!-- adds icon before -->
<a class="my-button icon-heart-a">do something else</a> <!-- adds icon after -->
```
CSS:
```css
[class^="icon-"]:before, [class*=" icon-"]:before, [class^="icon-"]:after, [class*=" icon-"]:after { font-family: "my_icons"; font-style: normal; font-weight: normal; speak: none; display: inline-block; text-decoration: inherit }
[class^="icon-"]:before, [class*=" icon-"]:before { margin-right: .5em }
[class^="icon-"]:after, [class*=" icon-"]:after { margin-left: .5em }

.icon-heart, .icon-heart-b:before, .icon-heart-a:after { content: '\48'; }
```
