### ISSUE TITLE
SCSS Varaibles

### ISSUE THREAD

**Issue by spAnser** [fontello/fontello#542]
It would be nice if we could get the `_fontello-codes.scss` to also contain variables or provide a `_fontello-variables.scss`

This would make it easier to write some custom css without have to manually map the exported codes to variables. So that we don't have to use the class names.

**Comment by puzrin** [comment]
Since it's difficult to support all possible formats, archive contains `config.json` with all data. If you use api to automate your workflow, you can write script to generate scss for your needs.

**Comment by spAnser** [comment]
Since I wasn't sure a length of answer I did that already.

Also since this wont be added. Here is the [grunt-regex-replace](https://github.com/bomsy/grunt-regex-replace) I wrote for converting the `_fontello-codes.scss` to a scss variable file.
```
    'regex-replace':
      fontello:
        src: ['src/fontello/scss/_fontello-codes.scss']
        actions: [
          {
            name: 'scss-variables'
            search: /^\.([a-z\-]+):before { content(: '\\[a-z0-9]+';) }(.*)$/gmi
            replace: (fullstring, codeName, code, comment) -> '$' + codeName + code + comment
          }
        ]
```
